### ISSUE TITLE
problem with HDF5Data (No conversion for layer: HDF5Data segmentation fault)

### ISSUE THREAD

**Issue by xiyinmsu** [nhynes/caffegraph#5]
Hi all, 

I am trying to use caffegraph to load a caffemodel and write to torch model .t7. 
I have installed it successfully. However when I run:

model = caffegraph.load('deply_file_path', 'model_file_path')
It will give the finally error:

[WARN] No conversion for layer: HDF5Data
Segmentation fault (core dumped)

so my caffemodel is simply a sequential network for regression with hdf5 data as input. 
In the deploy file, it only requires "data" as input without specifying to be hdf5. So I am wondering if anyone has encountered the same error and have a solution? Thanks!

**Comment by xiyinmsu** [comment]
i tried loadcaffe (https://github.com/szagoruyko/loadcaffe).
it does not work. 
Since I need to convert models that is not sequential so I guess I will have to use caffegraph anyway.

**Comment by nhynes** [comment]
I suspect that this might be easily fixed by simply ignoring the HDF5DataLayer [here](https://github.com/nhynes/caffegraph/blob/master/layers.cpp#L41). You're encouraged to submit a PR, but if you don't feel comfortable editing the source, you're also welcome to post the caffemodel+prototxt and I'll fix it for you!

**Comment by xiyinmsu** [comment]
Hi nhynes, thank you for your quick reply. I tried to edit that file but it still does not work. 
here is my caffemodel+prototxt. https://drive.google.com/open?id=0B6_vQ33ulVuzc20xRU9xZlZVR3c
It will be great if you could help on this.

**Comment by nhynes** [comment]
Fixed by 47262a1da29a5b2d3f6ac39e18bee8c55866f874. Thanks!

**Comment by xiyinmsu** [comment]
Thank you so very much for your solution!!!!! It works! I appreciate it very much.
